### ISSUE TITLE
amazing! any chance you would consider to also filter based on YAML property?

### ISSUE THREAD

**Issue by zeltak** [christianwannerstedt/obsidian-tags-overview#1]
Wow thx so much I have been waiting for something like this for ages!! :D :D  

any chance you would consider to also filter based on YAML property? so I can filter by `tag` and also `property` (ie `rating`)

thx so much for all your time and effort!

Z

**Comment by christianwannerstedt** [comment]
Thanks for your feedback, I'm glad you like it!

I've thought about adding more advanced filter settings, but at the same time don't want to make it too complex. Being able to filter on YAML properties would definitely add some value to it, it's not a bad idea at all, although I myself haven't felt a need for that particular feature yet. But I will give it some thoughts for sure :)

**Comment by christianwannerstedt** [comment]
Hey! This is now fixed in the latest release ([1.0.0](https://github.com/christianwannerstedt/obsidian-tags-overview/releases/tag/1.0.0)).

You can find additional information in the readme :)

**Comment by zeltak** [comment]
wow wow this is so incredible, I cant thank you enough!

been using it for the last hour and so and for me its a game changer! also the performance compared to queries from Dataview etc is insane (on my m1 mbp)

I have some other minor requests if you dont mind but ill open separate tickets if thats OK

thx so much again!

Z
