### ISSUE TITLE
adding cross-reference navigation and exploration layout

### ISSUE THREAD

**Issue by recspert** [christianwannerstedt/obsidian-tags-overview#10]
Hi!

First of all, thanks for the plugin! Previously opened issues show that this type of plugin is long awaited.

I have another enhancement idea for it, which I believe can benefit the community a lot. The plugin has all the necessary parts to restore and make easily accessible the functionality of the abandoned plugin called [Tab Navigator](https://github.com/alexobenauer/obsidian-tag-navigator) (ex. Cross-Reference Navigation). The plugin creates a convenient layout of notes categorized by tags and allows delving into lower levels of subtag hierarchies by mere mouse-clicking. It also makes use of the idea of related tags (that's where the "cross-reference" term comes from) that are nicely displayed within each category and are also fully navigable.

You can find the more detailed description of the cross-referencing idea and the layout [here](https://alexanderobenauer.com/labnotes/015/) and the short demo [here](https://alexanderobenauer.com/labnotes/exp001/).

It would be really nice to have similar functionality for easier navigation in the Tags Overview plugin!

**Comment by christianwannerstedt** [comment]
Hey! Thanks for the feedback and info regarding the tab navigator, it seems like a pretty nice plugin. It offers a lot of functionality that I don't currently plan to put into this plugin, but there was a lot that I liked when it came to the dashboard. I'll keep that in the back of my mind going forward. :)
