### ISSUE TITLE
ignore some file by giving a yaml tag

### ISSUE THREAD

**Issue by HananoshikaYomaru** [christianwannerstedt/obsidian-tags-overview#14]
I have a page index contains all the tags. It should be included in the tag overview as cross reference though.

**Comment by christianwannerstedt** [comment]
Hey! Yeah, this is a good idea, I'll put it in the backlog.

**Comment by christianwannerstedt** [comment]
Fixed in the latest release ([1.0.1](https://github.com/christianwannerstedt/obsidian-tags-overview/releases/tag/1.0.1))
It's now possible to ignore file with a property, you can find more info in the readme.
