### ISSUE TITLE
Add setting to default to List view, or remember last used view

### ISSUE THREAD

**Issue by RobinLandy** [christianwannerstedt/obsidian-tags-overview#16]
Tags Overview defaults to Compact View whenever Obsidian restarts (both on desktop and mobile). However, I always use it in List View.

Would it be possible to either:

1. Add a setting to choose the default view (i.e. Compact View or List View)
OR
2. Remember the last used view when Obsidian is restarted

Thank you. This plugin is incredibly useful!

Robin.

**Comment by christianwannerstedt** [comment]
Hey Robin, thanks for the feedback! This sounds very reasonable, I'll make sure to implement #2.

**Comment by christianwannerstedt** [comment]
This is now fixed in the latest release ([0.1.9](https://github.com/christianwannerstedt/obsidian-tags-overview/releases/tag/0.1.9))
