### ISSUE TITLE
support greater than etc ( >, =>) in yaml property filter ?

### ISSUE THREAD

**Issue by zeltak** [christianwannerstedt/obsidian-tags-overview#23]
this is a low priority request since you could use the `OR` operator but would be nice to also have the >, => etc option to quick filter based on numerical properties?

thx!

Z

**Comment by christianwannerstedt** [comment]
That is a good idea, I actually thought about adding a third filter type, so in addition to "Select" and "Text" there can be a "Numeric". Then it would be possible to replace the `AND` & `OR` for that filter type with the greater/lesser than comparison operators.

**Comment by christianwannerstedt** [comment]
Hey! The idea I mentioned above (with the numeric filter type) actually became a reality, and is now available in the latest release ([1.0.2](https://github.com/christianwannerstedt/obsidian-tags-overview/releases/tag/1.0.2))

**Comment by zeltak** [comment]
amazing thx so much!!!
