### ISSUE TITLE
Date values BC are sorted by absolute values

### ISSUE THREAD

**Issue by JoKo1959** [christianwannerstedt/obsidian-tags-overview#24]
There is a problem with sorting. I want to include historical dates (both AD and BC) in the YAML frontmatter of the files. I enter calendar dates BC in the YAML frontmatter with a leading negative sign; for example, -0715-01-01 for 1 January 715 BC. With "Sort files by properties (ascending)" all negative dates are sorted by their absolute values. Is there a solution to this? Thank you very much!

**Comment by christianwannerstedt** [comment]
Hey! This should be fixed in the latest release ([1.0.2](https://github.com/christianwannerstedt/obsidian-tags-overview/releases/tag/1.0.2))
