### ISSUE TITLE
request: add column names in the list view

### ISSUE THREAD

**Issue by zeltak** [christianwannerstedt/obsidian-tags-overview#26]
Hi again!

can't thank you enough for this plugin, it makes my life so much better each day :)

any chance that you can add column names in the list view:

![CleanShot 2024-01-20 at 17 53 12@2x](https://github.com/christianwannerstedt/obsidian-tags-overview/assets/498410/4d124286-4463-43a4-ad2c-0e5e4d2459df)

will make it easier to read through :)

best

Z

**Comment by christianwannerstedt** [comment]
Hi again! Yeah, I actually missed this myself sometimes, so I will probably make a setting to toggle the headers

**Comment by christianwannerstedt** [comment]
Okay, I decided to fix this one right away :), so now there is a new setting which controls this. You'll find it in the latest release ([1.0.3](https://github.com/christianwannerstedt/obsidian-tags-overview/releases/tag/1.0.3))

**Comment by zeltak** [comment]
this is so epic thx you so much!! now will wait patiently for the holy grail, saved searches :) :)
