### ISSUE TITLE
[Help] How to use this plugin?

### ISSUE THREAD

**Issue by ryadaj** [christianwannerstedt/obsidian-tags-overview#3]
Hi there,

I've downloaded and enabled this plugin but have no idea where the extended tags panel is or how to activate it. Please let me know!

Thank you.

**Comment by christianwannerstedt** [comment]
Hey!
After enabling the plugin it will show up as a tag-icon in the left sidebar:
<img width="934" alt="Screenshot 2023-10-10 at 07 58 29" src="https://github.com/christianwannerstedt/obsidian-tags-overview/assets/25314/753c8265-4808-4ad8-96de-b810080601d3">

When you click on it, the plugin will open on the right sidebar, and it's now possible to move it elsewhere if you want to. I will make sure to update the readme to make this a bit clearer, tnx.

**Comment by ryadaj** [comment]
Oh! That makes sense haha. Thank you very much. I have the ribbon hidden so that explains why I didn't see it.
