### ISSUE TITLE
Remove file repetition under a tag

### ISSUE THREAD

**Issue by SpeedyEgg** [christianwannerstedt/obsidian-tags-overview#4]
Hi,
Thanks for your nice work!
I was wondering if it's possible to remove the duplication of the same file under a tag (i.e., make it only appear once).
Here's my case: I use tags with Kanban in which many cards are attached with the same tag(s).
In the current tags-overview, the kanban file appears many times under the relevant tags.
Like this ↓
![Screenshot 2023-10-10 135853](https://github.com/christianwannerstedt/obsidian-tags-overview/assets/145581558/cb7f055a-5b25-4f59-ab28-5dbf6475c0cc)
As you can see, the duplication is a bit annoying and redundant.
I would like, at least to have an option to allow, any file to appear only once under a single tag.
Is this possible at the moment? Or could this be implemented in the future?
Thanks again!

**Comment by christianwannerstedt** [comment]
Hey, tnx for the feedback!

Strange thing I've never bumped into that issue before, but that's definitely a bug. I've fixed it now, and did just deploy a new version ([0.1.4](https://github.com/christianwannerstedt/obsidian-tags-overview/releases/tag/0.1.4)), so if you update the plugin it should look a lot better. :)

**Comment by SpeedyEgg** [comment]
Just updated and now it works perfectly!
Thanks a lot!
