### ISSUE TITLE
Refreshing the quick filter tags list

### ISSUE THREAD

**Issue by jean-** [christianwannerstedt/obsidian-tags-overview#8]
Hi there,

I am using this plugin and it's been great so far!

Whenever I create a new tag type (or remove one) for my notes though, I have to disable and enable the plugin so that it knows about my new tag in the quick filter list.
Is there another way to get the list refreshed ? Like a refresh button somewhere...

Thank you for the great work !

**Comment by christianwannerstedt** [comment]
Hey,
Thanks for bringing this to my attention. The idea is of course that the filter list should be updated automatically as soon as a tag is being created, updated or deleted. I will look into this issue as soon as possible.

**Comment by christianwannerstedt** [comment]
This issue is now fixed in the latest release ([0.1.6](https://github.com/christianwannerstedt/obsidian-tags-overview/releases/tag/0.1.6))
