### ISSUE TITLE
Lower hierarchy levels of nested tags

### ISSUE THREAD

**Issue by JoKo1959** [christianwannerstedt/obsidian-tags-overview#9]
I work with nested tags. Currently only the last hierarchy level of nested tags can be selected in the filter settings. It would be great if middle or lower hierarchy levels could be selected as well. 
Example: I am using the tags #person/man and #person/woman and want to select #person (i.e. men and women).
Thank you so much!

**Comment by christianwannerstedt** [comment]
Hey! Thanks for your feedback. Yeah, that is probably how everyone would expect it to work, so it would make very much sense to make sure it works that way. I'll look into it asap.

**Comment by christianwannerstedt** [comment]
This is now fixed in the latest release ([0.1.8](https://github.com/christianwannerstedt/obsidian-tags-overview/releases/tag/0.1.8))
